### ISSUE TITLE
[Suggestion] Balancing the cloak by consuming xp / duration

### ISSUE THREAD

**Issue by Nekkok** [Affehund/InvisibilityCloak#2]
This looks so cool! I have some suggestions to make:

- Make this wearable.
- Allow trinkets support, if possible.
- Make it consume experience/durability with each use. If you ask me, first option sounds more reliable.

Thank you!

**Comment by Affehund** [comment]
Thank you for all your ideas. 
But you can already wear the cloak in your chest slot or the trinkets chest/cape slot.
Making it consume xp sounds good. I will probation implement that soon.

**Comment by Affehund** [comment]
How much xp do you think should it consume?
